name: test-copa-extension
run-name: copa-extension-test
on: [push]

jobs:
  main-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: start_desktop
        uses: docker/desktop-action/start@v0.3.6

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Edit Docker Desktop setting file
        shell: bash
        run: |
          echo $(jq '. += {onlyMarketplaceExtensions: false}' ~/.docker/desktop/settings.json) > ~/.docker/desktop/settings.json
          echo ~/.docker/desktop/settings.json

      - name: Validate metadata
        run: docker extension validate ./metadata.json

      - name: Build extension
        run: docker build -t copacetic/copacetic-docker-desktop-extension .

      - name: Install extension
        run: docker extension install copacetic/copacetic-docker-desktop-extension -f

      - name: Run Jest tests
        run: npm test
